.\" Manpage for vmpserverd
.TH vmpserverd 1 "26 September 2023" "0.1.0" "User Commands"
.SH NAME
vmpserverd \- The VMP (virtual streaming processor) Server Daemon
.SH SYNOPSIS
.B vmpserverd
[\fIOPTION\fR]...
.SH DESCRIPTION
\fBvmpserverd\fR is the VMP (virtual streaming processor) Server Daemon.
It is the core of the VMP system, and responsible for managing the
video processing pipeline, RTSP server, and management interface.
.PP
The following options are available:
.TP
.B \-h, \-\-help
Prints the help message.
.TP
.B \-v, \-\-version
Prints the version information.
.TP
.BI \-c, \-\-config= "PATH"
Specifies the path to the configuration file.
.SH AUTHOR
This manual page was written by Hugo Melder <contact@hugomelder.com>.